# Builder Image
FROM pipeplusplus:amd64-dev

ARG VERSION=Release

USER root

RUN mkdir /app/build -p
COPY ./cmake /app/cmake
COPY ./libs /app/libs
COPY ./CMakeLists.txt /app/CMakeLists.txt
WORKDIR /app/build
RUN cmake -DON_HOST=OFF -DDEVICE_ARCH=amd64 -DSYSTEM_NAME=FCPO -DCMAKE_BUILD_TYPE=VERSION ..
RUN make -j$(nproc)
COPY ./jsons /app/jsons

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone