FROM pipeplusplus:base-amd64

USER root

# Torch
ARG TORCH_FILE=libtorch-cxx11-abi-shared-with-deps-1.11.0+cu115.zip
ARG TORCH_LINK=https://download.pytorch.org/libtorch/cu115/libtorch-cxx11-abi-shared-with-deps-1.11.0%2Bcu115.zip
RUN wget ${TORCH_LINK} && \
    unzip ${TORCH_FILE} && \
    rm ${TORCH_FILE} 

RUN apt-get update && apt-get install -y libpqxx-dev
ARG user=soulsaver
ARG host_uid=1001
ARG host_gid=1001

USER ${user}
    
ENV HOME=/home/${user}

CMD [ "/bin/bash" ]
