# Builder Image
FROM pipeplusplus:torch

ARG VERSION=Release

USER root

RUN mkdir /app/build -p
COPY ./cmake /app/cmake
COPY ./libs /app/libs
COPY ./CMakeLists.txt /app/CMakeLists.txt
WORKDIR /app/build
RUN cmake -DON_HOST=OFF -DDEVICE_ARCH=amd64 -DSYSTEM_NAME=FCPO -DCMAKE_BUILD_TYPE=VERSION ..
RUN make -j$(nproc)
COPY ./jsons /app/jsons